FROM node:22.2.0-alpine3.20 as buildstage
LABEL maintainer="codefrantic.com"

WORKDIR /app

# COPY ./requirements.txt /tmp/requirements.txt
COPY ./package.json .

RUN npm install

COPY . .


RUN npm run build



FROM nginx:stable-alpine

# /app/build - this is where react
# places the built files from the
# previous stage.
COPY --from=buildstage /app/build /usr/share/nginx/html

ARG DEFAULT_PORT=80
ENV PORT $DEFAULT_PORT
EXPOSE $PORT

CMD ["nginx", "-g", "daemon off;"]
