apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: fastapi-microservices-demo
deploy:
  kubectl:
    manifests:
      # - ./infra/kube/*.yaml
      - ./infra/kube/auth-pg.secret.dev.yaml
      - ./infra/kube/auth-pg.depl.yaml      
              
      - ./infra/kube/auth.config.yaml
      - ./infra/kube/auth.secret.dev.yaml
      - ./infra/kube/auth.depl.yaml
      - ./infra/kube/auth.srv.yaml
      - ./infra/kube/auth.migration.yaml


      - ./infra/kube/items-pg.secret.dev.yaml
      - ./infra/kube/items-pg.depl.yaml      
              
      - ./infra/kube/items.config.yaml
      - ./infra/kube/items.depl.yaml
      - ./infra/kube/items.srv.yaml
      - ./infra/kube/items.migration.yaml


      - ./infra/kube/client.depl.yaml
      - ./infra/kube/client.srv.yaml

      - ./infra/kube/ingress.srv.yaml

  # hooks:
  #   after:
  #     - host:
  #         command: ["kubectl", "wait", "--for=condition=complete", "job/auth-migration"]

build:
  local:
    push: false
  artifacts:
    - image: faikingyip/fastapi-microservices-demo-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.py"
            dest: .
    - image: faikingyip/fastapi-microservices-demo-items
      context: items
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.py"
            dest: .
    - image: faikingyip/fastapi-microservices-demo-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.jsx"
            dest: .
          - src: "**/*.css"
            dest: .


