apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: fastapi-microservices-demo
deploy:
  kubectl:
    manifests:
      - ./infra/kube/*.yaml
  # hooks:
  #   after:
  #     - host:
  #         command: ["kubectl", "wait", "--for=condition=complete", "job/auth-migration"]
  # annotations:
  #   post-deploy:
  #     - kubectl wait --for=condition=complete job/auth-migration
build:
  local:
    push: false
  artifacts:
    - image: faikingyip/fastapi-microservices-demo-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.py"
            dest: .
    - image: faikingyip/fastapi-microservices-demo-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.jsx"
            dest: .
          - src: "**/*.css"
            dest: .


