"""Added version to DbAccount

Revision ID: 4b8ffc00e909
Revises: 61dcb1864671
Create Date: 2024-07-16 16:50:54.773837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8ffc00e909'
down_revision: Union[str, None] = '61dcb1864671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'version')
    # ### end Alembic commands ###
