"""added versioning for DbAccount and removed last_trans_id column.

Revision ID: a13d0d3253d8
Revises: 4b8ffc00e909
Create Date: 2024-07-16 17:29:05.428628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13d0d3253d8'
down_revision: Union[str, None] = '4b8ffc00e909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'last_trans_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('last_trans_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
