"""updated DbTransaction to use version instead of last_trans_id

Revision ID: 266b5707860f
Revises: b2eb00cc93f8
Create Date: 2024-07-17 14:30:02.878183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266b5707860f'
down_revision: Union[str, None] = 'b2eb00cc93f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('version', sa.Integer(), nullable=False))
    op.drop_constraint('transaction_last_trans_id_key', 'transaction', type_='unique')
    op.create_unique_constraint('uix_user_version', 'transaction', ['user_id', 'version'])
    op.drop_column('transaction', 'last_trans_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('last_trans_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('uix_user_version', 'transaction', type_='unique')
    op.create_unique_constraint('transaction_last_trans_id_key', 'transaction', ['last_trans_id'])
    op.drop_column('transaction', 'version')
    # ### end Alembic commands ###
