apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: faikingyip/fastapi-microservices-demo-auth:latest
          env:
            - name: ENV
              value: Production
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-pg-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-srv-secret
                  key: JWT_SECRET_KEY
          envFrom:
            - configMapRef:
                name: auth-config
